# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- azure-pipelines

resources:
- repo: self

variables:
- group: MY_PROPERTIES
- name: NAMESPACE
  value: dev
- name: APP_NAME
  value: "gitops-demo-system"
- name: HELM_CHART
  value: "https://github.com/ozyohthree/gitops-demo-deploy-config/releases/download/deploy-0.1.2/deploy-0.1.2.tgz"
- name: GIT_COMMIT
  value: $(Build.SourceVersion)
- name: GIT_BRANCH
  value: $(Build.SourceBranchName)
- name: TAG_VERSION
  value: $(GIT_COMMIT)
- name: IMAGE_TAG
  value: "$(QUAY_NAME)/$(QUAY_USER)/$(APP_NAME):$TAG_VERSION"

stages:
  - stage: BuildAndPushDockerImage
    displayName: 'Build image and push to quay.io'
    jobs:
    - job: BuildAndPush
      displayName: Docker-Build
      pool:
        vmImage: ubuntu-latest
      steps:
      # - task: Docker@0
      #   name: build_docker_image
      #   displayName: 'Build Application Docker Image'
      #   inputs:
      #     containerregistrytype: 'Container Registry'
      #     action: 'Build an image'
      #     dockerFile: '**/Dockerfile.build'
      #     imageName: '$(IMAGE_TAG)' 
      #     #'$(Build.Repository.Name):$(Build.BuildId)'
        
      - task: Bash@3
        name: push_image_to_registry
        displayName: 'Push image to Quay registry'
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            # echo "TAG_VERSION: $(GIT_COMMIT)"
            # echo "##vso[task.setvariable variable=FULL_IMAGE_TAG;]release-$(GIT_COMMIT)"
            echo "$(IMAGE_TAG)"
            docker images
            # docker login -u="$(QUAY_USER)" -p="$(QUAY_PASS)" $(QUAY_NAME)
            # docker push $(IMAGE_TAG)
           